name: Test feature PR

env:
  PORT: "8081"
  HEROKU_SLUG_COMMIT: "0000000000000000000000000000000000000000"
  JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET__GH_ACTIONS }}

on:
  pull_request:
    branches:
      - develop

jobs:
  test_u:
    name: Unit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci

      - name: Run unit tests
        id: run_unit_tests
        run: npm run test:u
        continue-on-error: true

      - name: Save test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./*.log

      - name: Fail if needed
        if: steps.run_unit_tests.outcome == 'failure' # https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
        run: exit 1
