name: Test feature PR

env:
  PORT: "8081"
  HEROKU_SLUG_COMMIT: "0000000000000000000000000000000000000000"
  JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET__GH_ACTIONS }}

on:
  pull_request:
    branches:
      - develop

jobs:
  test_u:
    name: Unit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run test:u
